// GENERATED by `pnpm program:idl` from programs/target/types/match_pools.ts.
// Do not edit by hand. Review the diff whenever the on-chain interface changes.

export type MatchPools = {
  address: '92EVZikCaJ1SXTJAq7e8NzzZg5zLKjK2LyX14SQeQRfE';
  metadata: {
    name: 'matchPools';
    version: '0.1.0';
    spec: '0.1.0';
    description: 'AquaStock Match Pools: a sponsor-funded, vesting match on Token-2022 deposits';
  };
  instructions: [
    {
      name: 'claimVested';
      discriminator: [208, 190, 166, 114, 203, 225, 140, 208];
      accounts: [
        {
          name: 'saver';
          signer: true;
          relations: ['position'];
        },
        {
          name: 'pool';
          writable: true;
          relations: ['position'];
        },
        {
          name: 'position';
          writable: true;
        },
        {
          name: 'mint';
          relations: ['pool'];
        },
        {
          name: 'vault';
          writable: true;
          relations: ['pool'];
        },
        {
          name: 'saverTokenAccount';
          writable: true;
        },
        {
          name: 'tokenProgram';
          address: 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb';
        },
      ];
      args: [];
    },
    {
      name: 'closePosition';
      discriminator: [123, 134, 81, 0, 49, 68, 98, 98];
      accounts: [
        {
          name: 'saver';
          writable: true;
          signer: true;
          relations: ['position'];
        },
        {
          name: 'pool';
          relations: ['position'];
        },
        {
          name: 'position';
          docs: [
            'Closable only once the deposit is withdrawn and every reserved match token is',
            'claimed, so closing can never strand funds. Rent returns to the saver.',
          ];
          writable: true;
        },
      ];
      args: [];
    },
    {
      name: 'createPool';
      discriminator: [233, 146, 209, 142, 207, 104, 64, 188];
      accounts: [
        {
          name: 'sponsor';
          writable: true;
          signer: true;
        },
        {
          name: 'mint';
          docs: [
            'Must be a Token-2022 mint; the extension set is checked in the handler.',
          ];
        },
        {
          name: 'config';
          pda: {
            seeds: [
              {
                kind: 'const';
                value: [99, 111, 110, 102, 105, 103];
              },
            ];
          };
        },
        {
          name: 'pool';
          writable: true;
          pda: {
            seeds: [
              {
                kind: 'const';
                value: [112, 111, 111, 108];
              },
              {
                kind: 'account';
                path: 'sponsor';
              },
              {
                kind: 'arg';
                path: 'params.poolId';
              },
            ];
          };
        },
        {
          name: 'vault';
          docs: [
            "Sized by Anchor from the mint's required account extensions.",
          ];
          writable: true;
          pda: {
            seeds: [
              {
                kind: 'const';
                value: [118, 97, 117, 108, 116];
              },
              {
                kind: 'account';
                path: 'pool';
              },
            ];
          };
        },
        {
          name: 'tokenProgram';
          address: 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb';
        },
        {
          name: 'systemProgram';
          address: '11111111111111111111111111111111';
        },
      ];
      args: [
        {
          name: 'params';
          type: {
            defined: {
              name: 'createPoolParams';
            };
          };
        },
      ];
    },
    {
      name: 'deposit';
      discriminator: [242, 35, 198, 137, 82, 225, 242, 182];
      accounts: [
        {
          name: 'saver';
          writable: true;
          signer: true;
        },
        {
          name: 'pool';
          writable: true;
        },
        {
          name: 'position';
          docs: [
            'One position per saver per pool, so a second deposit fails at `init`.',
          ];
          writable: true;
          pda: {
            seeds: [
              {
                kind: 'const';
                value: [112, 111, 115, 105, 116, 105, 111, 110];
              },
              {
                kind: 'account';
                path: 'pool';
              },
              {
                kind: 'account';
                path: 'saver';
              },
            ];
          };
        },
        {
          name: 'mint';
          relations: ['pool'];
        },
        {
          name: 'vault';
          writable: true;
          relations: ['pool'];
        },
        {
          name: 'saverTokenAccount';
          writable: true;
        },
        {
          name: 'tokenProgram';
          address: 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb';
        },
        {
          name: 'systemProgram';
          address: '11111111111111111111111111111111';
        },
      ];
      args: [
        {
          name: 'amount';
          type: 'u64';
        },
        {
          name: 'minMatch';
          type: 'u64';
        },
      ];
    },
    {
      name: 'fundMatch';
      discriminator: [114, 40, 57, 162, 161, 146, 87, 223];
      accounts: [
        {
          name: 'sponsor';
          signer: true;
          relations: ['pool'];
        },
        {
          name: 'pool';
          writable: true;
        },
        {
          name: 'mint';
          relations: ['pool'];
        },
        {
          name: 'vault';
          writable: true;
          relations: ['pool'];
        },
        {
          name: 'sponsorTokenAccount';
          writable: true;
        },
        {
          name: 'tokenProgram';
          address: 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb';
        },
      ];
      args: [
        {
          name: 'amount';
          type: 'u64';
        },
      ];
    },
    {
      name: 'initConfig';
      discriminator: [23, 235, 115, 232, 168, 96, 1, 231];
      accounts: [
        {
          name: 'authority';
          docs: [
            "Must be the program's upgrade authority. Whoever can replace the code can",
            'already do anything, so this adds no new trust; it stops a stranger from',
            'front-running the deploy and choosing the mint.',
          ];
          writable: true;
          signer: true;
        },
        {
          name: 'config';
          writable: true;
          pda: {
            seeds: [
              {
                kind: 'const';
                value: [99, 111, 110, 102, 105, 103];
              },
            ];
          };
        },
        {
          name: 'mint';
        },
        {
          name: 'program';
          address: '92EVZikCaJ1SXTJAq7e8NzzZg5zLKjK2LyX14SQeQRfE';
        },
        {
          name: 'programData';
        },
        {
          name: 'tokenProgram';
          address: 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb';
        },
        {
          name: 'systemProgram';
          address: '11111111111111111111111111111111';
        },
      ];
      args: [];
    },
    {
      name: 'reclaimUnmatched';
      discriminator: [226, 3, 118, 204, 148, 141, 67, 178];
      accounts: [
        {
          name: 'sponsor';
          signer: true;
          relations: ['pool'];
        },
        {
          name: 'pool';
          writable: true;
        },
        {
          name: 'mint';
          relations: ['pool'];
        },
        {
          name: 'vault';
          writable: true;
          relations: ['pool'];
        },
        {
          name: 'sponsorTokenAccount';
          writable: true;
        },
        {
          name: 'tokenProgram';
          address: 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb';
        },
      ];
      args: [];
    },
    {
      name: 'withdraw';
      discriminator: [183, 18, 70, 156, 148, 109, 161, 34];
      accounts: [
        {
          name: 'saver';
          signer: true;
          relations: ['position'];
        },
        {
          name: 'pool';
          writable: true;
          relations: ['position'];
        },
        {
          name: 'position';
          writable: true;
        },
        {
          name: 'mint';
          relations: ['pool'];
        },
        {
          name: 'vault';
          writable: true;
          relations: ['pool'];
        },
        {
          name: 'saverTokenAccount';
          writable: true;
        },
        {
          name: 'tokenProgram';
          address: 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb';
        },
      ];
      args: [];
    },
  ];
  accounts: [
    {
      name: 'config';
      discriminator: [155, 12, 170, 224, 30, 250, 204, 130];
    },
    {
      name: 'pool';
      discriminator: [241, 154, 109, 4, 17, 177, 109, 188];
    },
    {
      name: 'position';
      discriminator: [170, 188, 143, 228, 122, 64, 247, 208];
    },
  ];
  events: [
    {
      name: 'claimed';
      discriminator: [217, 192, 123, 72, 108, 150, 248, 33];
    },
    {
      name: 'configInitialized';
      discriminator: [181, 49, 200, 156, 19, 167, 178, 91];
    },
    {
      name: 'deposited';
      discriminator: [111, 141, 26, 45, 161, 35, 100, 57];
    },
    {
      name: 'matchFunded';
      discriminator: [1, 37, 9, 113, 47, 119, 3, 100];
    },
    {
      name: 'poolCreated';
      discriminator: [202, 44, 41, 88, 104, 220, 157, 82];
    },
    {
      name: 'positionClosed';
      discriminator: [157, 163, 227, 228, 13, 97, 138, 121];
    },
    {
      name: 'unmatchedReclaimed';
      discriminator: [28, 130, 1, 147, 9, 186, 88, 252];
    },
    {
      name: 'withdrawn';
      discriminator: [20, 89, 223, 198, 194, 124, 219, 13];
    },
  ];
  errors: [
    {
      code: 6000;
      name: 'mathOverflow';
      msg: 'Arithmetic overflow';
    },
    {
      code: 6001;
      name: 'unauthorized';
      msg: 'Only the pool sponsor can do this';
    },
    {
      code: 6002;
      name: 'wrongMint';
      msg: 'The mint does not match this pool';
    },
    {
      code: 6003;
      name: 'wrongVault';
      msg: 'The vault does not match this pool';
    },
    {
      code: 6004;
      name: 'invalidMatchBps';
      msg: 'Match ratio must be between 1 and 10000 basis points';
    },
    {
      code: 6005;
      name: 'invalidPerSaverCap';
      msg: 'Per-saver cap must be greater than zero';
    },
    {
      code: 6006;
      name: 'invalidVestingDuration';
      msg: 'Vesting period is outside the allowed range';
    },
    {
      code: 6007;
      name: 'invalidPoolWindow';
      msg: 'Deposit window must end in the future and within the allowed range';
    },
    {
      code: 6008;
      name: 'invalidMintDecimals';
      msg: 'Mint decimals are not supported';
    },
    {
      code: 6009;
      name: 'unsupportedMintExtension';
      msg: 'Mint has an extension this program does not accept';
    },
    {
      code: 6010;
      name: 'transferHookEnabled';
      msg: 'Mint has an enabled transfer hook';
    },
    {
      code: 6011;
      name: 'frozenByDefault';
      msg: 'Mint creates token accounts frozen by default';
    },
    {
      code: 6012;
      name: 'mintPaused';
      msg: 'Mint transfers are paused by the issuer';
    },
    {
      code: 6013;
      name: 'zeroAmount';
      msg: 'Amount must be greater than zero';
    },
    {
      code: 6014;
      name: 'poolEnded';
      msg: 'The deposit window has closed';
    },
    {
      code: 6015;
      name: 'poolNotEnded';
      msg: 'The pool has not ended yet';
    },
    {
      code: 6016;
      name: 'depositExceedsCap';
      msg: 'Deposit exceeds the per-saver cap';
    },
    {
      code: 6017;
      name: 'budgetExhausted';
      msg: 'The match budget is exhausted';
    },
    {
      code: 6018;
      name: 'matchBelowMinimum';
      msg: 'Match available is below the minimum requested';
    },
    {
      code: 6019;
      name: 'nothingToClaim';
      msg: 'There is no vested match to claim';
    },
    {
      code: 6020;
      name: 'alreadyWithdrawn';
      msg: 'This position has already been withdrawn';
    },
    {
      code: 6021;
      name: 'mintNotAllowed';
      msg: 'This mint is not the one this deployment allows';
    },
    {
      code: 6022;
      name: 'nothingToReclaim';
      msg: 'There is no unreserved budget to reclaim';
    },
    {
      code: 6023;
      name: 'positionStillActive';
      msg: 'The position still has a deposit or unclaimed match';
    },
  ];
  types: [
    {
      name: 'claimed';
      type: {
        kind: 'struct';
        fields: [
          {
            name: 'pool';
            type: 'pubkey';
          },
          {
            name: 'saver';
            type: 'pubkey';
          },
          {
            name: 'amount';
            type: 'u64';
          },
          {
            name: 'totalClaimed';
            type: 'u64';
          },
        ];
      };
    },
    {
      name: 'config';
      docs: [
        "Deployment-wide settings, written once by the program's upgrade authority. There is",
        'no update instruction, so the allowed mint cannot change after `init_config`.',
      ];
      type: {
        kind: 'struct';
        fields: [
          {
            name: 'admin';
            docs: ['The upgrade authority that initialised this deployment.'];
            type: 'pubkey';
          },
          {
            name: 'allowedMint';
            docs: [
              'The only mint a pool may hold: SPYx on mainnet, the replica on devnet.',
            ];
            type: 'pubkey';
          },
          {
            name: 'bump';
            type: 'u8';
          },
        ];
      };
    },
    {
      name: 'configInitialized';
      type: {
        kind: 'struct';
        fields: [
          {
            name: 'admin';
            type: 'pubkey';
          },
          {
            name: 'allowedMint';
            type: 'pubkey';
          },
        ];
      };
    },
    {
      name: 'createPoolParams';
      type: {
        kind: 'struct';
        fields: [
          {
            name: 'poolId';
            docs: ['Lets one sponsor run several pools.'];
            type: 'u64';
          },
          {
            name: 'matchBps';
            docs: ['Match per deposit in basis points; 10_000 is 1:1.'];
            type: 'u16';
          },
          {
            name: 'perSaverCap';
            docs: ['Largest deposit one saver may make, in raw units.'];
            type: 'u64';
          },
          {
            name: 'vestingSeconds';
            type: 'i64';
          },
          {
            name: 'endsAt';
            docs: ['Unix time when deposits and funding stop.'];
            type: 'i64';
          },
        ];
      };
    },
    {
      name: 'deposited';
      type: {
        kind: 'struct';
        fields: [
          {
            name: 'pool';
            type: 'pubkey';
          },
          {
            name: 'saver';
            type: 'pubkey';
          },
          {
            name: 'amount';
            type: 'u64';
          },
          {
            name: 'matchReserved';
            type: 'u64';
          },
          {
            name: 'startedAt';
            type: 'i64';
          },
        ];
      };
    },
    {
      name: 'matchFunded';
      type: {
        kind: 'struct';
        fields: [
          {
            name: 'pool';
            type: 'pubkey';
          },
          {
            name: 'sponsor';
            type: 'pubkey';
          },
          {
            name: 'amount';
            type: 'u64';
          },
          {
            name: 'budgetTotal';
            type: 'u64';
          },
        ];
      };
    },
    {
      name: 'pool';
      docs: [
        'One sponsor-funded match pool. All amounts are raw token units.',
        '',
        'Vault accounting, which the tests assert:',
        '`vault balance >= (budget_total - claimed) + deposits_total`.',
        'Logic never reads the vault balance, so an unsolicited transfer into the',
        'vault cannot skew it.',
      ];
      type: {
        kind: 'struct';
        fields: [
          {
            name: 'sponsor';
            type: 'pubkey';
          },
          {
            name: 'mint';
            type: 'pubkey';
          },
          {
            name: 'vault';
            type: 'pubkey';
          },
          {
            name: 'poolId';
            type: 'u64';
          },
          {
            name: 'matchBps';
            type: 'u16';
          },
          {
            name: 'perSaverCap';
            docs: ['Largest deposit a single saver may make.'];
            type: 'u64';
          },
          {
            name: 'vestingSeconds';
            type: 'i64';
          },
          {
            name: 'createdAt';
            type: 'i64';
          },
          {
            name: 'endsAt';
            docs: [
              'Deposits and funding stop at this time; the sponsor may then reclaim unreserved budget.',
            ];
            type: 'i64';
          },
          {
            name: 'budgetTotal';
            docs: ['Match the sponsor has funded and not reclaimed.'];
            type: 'u64';
          },
          {
            name: 'reserved';
            docs: [
              'Match reserved for savers, claimed or not. Never exceeds `budget_total`.',
            ];
            type: 'u64';
          },
          {
            name: 'claimed';
            docs: ['Reserved match already paid out.'];
            type: 'u64';
          },
          {
            name: 'depositsTotal';
            docs: ['Saver principal currently held in the vault.'];
            type: 'u64';
          },
          {
            name: 'bump';
            type: 'u8';
          },
          {
            name: 'vaultBump';
            type: 'u8';
          },
        ];
      };
    },
    {
      name: 'poolCreated';
      type: {
        kind: 'struct';
        fields: [
          {
            name: 'pool';
            type: 'pubkey';
          },
          {
            name: 'sponsor';
            type: 'pubkey';
          },
          {
            name: 'mint';
            type: 'pubkey';
          },
          {
            name: 'poolId';
            type: 'u64';
          },
          {
            name: 'matchBps';
            type: 'u16';
          },
          {
            name: 'perSaverCap';
            type: 'u64';
          },
          {
            name: 'vestingSeconds';
            type: 'i64';
          },
          {
            name: 'endsAt';
            type: 'i64';
          },
        ];
      };
    },
    {
      name: 'position';
      docs: ["One saver's stake in one pool. A saver deposits once per pool."];
      type: {
        kind: 'struct';
        fields: [
          {
            name: 'pool';
            type: 'pubkey';
          },
          {
            name: 'saver';
            type: 'pubkey';
          },
          {
            name: 'deposited';
            docs: ['Principal still in the vault; zero once withdrawn.'];
            type: 'u64';
          },
          {
            name: 'matchReserved';
            docs: ['Match reserved for this position, after any forfeiture.'];
            type: 'u64';
          },
          {
            name: 'matchClaimed';
            type: 'u64';
          },
          {
            name: 'startedAt';
            type: 'i64';
          },
          {
            name: 'settled';
            docs: [
              'Set by `withdraw`. The unvested match is forfeited at that moment, so',
              'what remains is fully vested and vesting must not be recomputed.',
            ];
            type: 'bool';
          },
          {
            name: 'bump';
            type: 'u8';
          },
        ];
      };
    },
    {
      name: 'positionClosed';
      type: {
        kind: 'struct';
        fields: [
          {
            name: 'pool';
            type: 'pubkey';
          },
          {
            name: 'saver';
            type: 'pubkey';
          },
        ];
      };
    },
    {
      name: 'unmatchedReclaimed';
      type: {
        kind: 'struct';
        fields: [
          {
            name: 'pool';
            type: 'pubkey';
          },
          {
            name: 'sponsor';
            type: 'pubkey';
          },
          {
            name: 'amount';
            type: 'u64';
          },
          {
            name: 'budgetTotal';
            type: 'u64';
          },
        ];
      };
    },
    {
      name: 'withdrawn';
      type: {
        kind: 'struct';
        fields: [
          {
            name: 'pool';
            type: 'pubkey';
          },
          {
            name: 'saver';
            type: 'pubkey';
          },
          {
            name: 'principal';
            type: 'u64';
          },
          {
            name: 'forfeited';
            type: 'u64';
          },
        ];
      };
    },
  ];
  constants: [
    {
      name: 'bpsDenominator';
      type: 'u64';
      value: '10000';
    },
    {
      name: 'configSeed';
      type: 'bytes';
      value: '[99, 111, 110, 102, 105, 103]';
    },
    {
      name: 'maxMatchBps';
      docs: ['Match ratio ceiling: 10_000 bps is a 1:1 match.'];
      type: 'u16';
      value: '10000';
    },
    {
      name: 'maxPoolWindowSeconds';
      docs: [
        'Longest deposit window a pool may declare, counted from creation.',
      ];
      type: 'i64';
      value: '157680000';
    },
    {
      name: 'maxVestingSeconds';
      type: 'i64';
      value: '157680000';
    },
    {
      name: 'mintDecimals';
      docs: [
        'Every supported mint (SPYx and the devnet replica) uses 8 decimals.',
      ];
      type: 'u8';
      value: '8';
    },
    {
      name: 'minVestingSeconds';
      docs: [
        'Floor is low on purpose so a demo pool can vest in minutes. Real pools use months.',
      ];
      type: 'i64';
      value: '30';
    },
    {
      name: 'poolSeed';
      type: 'bytes';
      value: '[112, 111, 111, 108]';
    },
    {
      name: 'positionSeed';
      type: 'bytes';
      value: '[112, 111, 115, 105, 116, 105, 111, 110]';
    },
    {
      name: 'vaultSeed';
      type: 'bytes';
      value: '[118, 97, 117, 108, 116]';
    },
  ];
};

export const matchPoolsIdl: MatchPools = {
  address: '92EVZikCaJ1SXTJAq7e8NzzZg5zLKjK2LyX14SQeQRfE',
  metadata: {
    name: 'matchPools',
    version: '0.1.0',
    spec: '0.1.0',
    description:
      'AquaStock Match Pools: a sponsor-funded, vesting match on Token-2022 deposits',
  },
  instructions: [
    {
      name: 'claimVested',
      discriminator: [208, 190, 166, 114, 203, 225, 140, 208],
      accounts: [
        {
          name: 'saver',
          signer: true,
          relations: ['position'],
        },
        {
          name: 'pool',
          writable: true,
          relations: ['position'],
        },
        {
          name: 'position',
          writable: true,
        },
        {
          name: 'mint',
          relations: ['pool'],
        },
        {
          name: 'vault',
          writable: true,
          relations: ['pool'],
        },
        {
          name: 'saverTokenAccount',
          writable: true,
        },
        {
          name: 'tokenProgram',
          address: 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb',
        },
      ],
      args: [],
    },
    {
      name: 'closePosition',
      discriminator: [123, 134, 81, 0, 49, 68, 98, 98],
      accounts: [
        {
          name: 'saver',
          writable: true,
          signer: true,
          relations: ['position'],
        },
        {
          name: 'pool',
          relations: ['position'],
        },
        {
          name: 'position',
          docs: [
            'Closable only once the deposit is withdrawn and every reserved match token is',
            'claimed, so closing can never strand funds. Rent returns to the saver.',
          ],
          writable: true,
        },
      ],
      args: [],
    },
    {
      name: 'createPool',
      discriminator: [233, 146, 209, 142, 207, 104, 64, 188],
      accounts: [
        {
          name: 'sponsor',
          writable: true,
          signer: true,
        },
        {
          name: 'mint',
          docs: [
            'Must be a Token-2022 mint; the extension set is checked in the handler.',
          ],
        },
        {
          name: 'config',
          pda: {
            seeds: [
              {
                kind: 'const',
                value: [99, 111, 110, 102, 105, 103],
              },
            ],
          },
        },
        {
          name: 'pool',
          writable: true,
          pda: {
            seeds: [
              {
                kind: 'const',
                value: [112, 111, 111, 108],
              },
              {
                kind: 'account',
                path: 'sponsor',
              },
              {
                kind: 'arg',
                path: 'params.poolId',
              },
            ],
          },
        },
        {
          name: 'vault',
          docs: [
            "Sized by Anchor from the mint's required account extensions.",
          ],
          writable: true,
          pda: {
            seeds: [
              {
                kind: 'const',
                value: [118, 97, 117, 108, 116],
              },
              {
                kind: 'account',
                path: 'pool',
              },
            ],
          },
        },
        {
          name: 'tokenProgram',
          address: 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb',
        },
        {
          name: 'systemProgram',
          address: '11111111111111111111111111111111',
        },
      ],
      args: [
        {
          name: 'params',
          type: {
            defined: {
              name: 'createPoolParams',
            },
          },
        },
      ],
    },
    {
      name: 'deposit',
      discriminator: [242, 35, 198, 137, 82, 225, 242, 182],
      accounts: [
        {
          name: 'saver',
          writable: true,
          signer: true,
        },
        {
          name: 'pool',
          writable: true,
        },
        {
          name: 'position',
          docs: [
            'One position per saver per pool, so a second deposit fails at `init`.',
          ],
          writable: true,
          pda: {
            seeds: [
              {
                kind: 'const',
                value: [112, 111, 115, 105, 116, 105, 111, 110],
              },
              {
                kind: 'account',
                path: 'pool',
              },
              {
                kind: 'account',
                path: 'saver',
              },
            ],
          },
        },
        {
          name: 'mint',
          relations: ['pool'],
        },
        {
          name: 'vault',
          writable: true,
          relations: ['pool'],
        },
        {
          name: 'saverTokenAccount',
          writable: true,
        },
        {
          name: 'tokenProgram',
          address: 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb',
        },
        {
          name: 'systemProgram',
          address: '11111111111111111111111111111111',
        },
      ],
      args: [
        {
          name: 'amount',
          type: 'u64',
        },
        {
          name: 'minMatch',
          type: 'u64',
        },
      ],
    },
    {
      name: 'fundMatch',
      discriminator: [114, 40, 57, 162, 161, 146, 87, 223],
      accounts: [
        {
          name: 'sponsor',
          signer: true,
          relations: ['pool'],
        },
        {
          name: 'pool',
          writable: true,
        },
        {
          name: 'mint',
          relations: ['pool'],
        },
        {
          name: 'vault',
          writable: true,
          relations: ['pool'],
        },
        {
          name: 'sponsorTokenAccount',
          writable: true,
        },
        {
          name: 'tokenProgram',
          address: 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb',
        },
      ],
      args: [
        {
          name: 'amount',
          type: 'u64',
        },
      ],
    },
    {
      name: 'initConfig',
      discriminator: [23, 235, 115, 232, 168, 96, 1, 231],
      accounts: [
        {
          name: 'authority',
          docs: [
            "Must be the program's upgrade authority. Whoever can replace the code can",
            'already do anything, so this adds no new trust; it stops a stranger from',
            'front-running the deploy and choosing the mint.',
          ],
          writable: true,
          signer: true,
        },
        {
          name: 'config',
          writable: true,
          pda: {
            seeds: [
              {
                kind: 'const',
                value: [99, 111, 110, 102, 105, 103],
              },
            ],
          },
        },
        {
          name: 'mint',
        },
        {
          name: 'program',
          address: '92EVZikCaJ1SXTJAq7e8NzzZg5zLKjK2LyX14SQeQRfE',
        },
        {
          name: 'programData',
        },
        {
          name: 'tokenProgram',
          address: 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb',
        },
        {
          name: 'systemProgram',
          address: '11111111111111111111111111111111',
        },
      ],
      args: [],
    },
    {
      name: 'reclaimUnmatched',
      discriminator: [226, 3, 118, 204, 148, 141, 67, 178],
      accounts: [
        {
          name: 'sponsor',
          signer: true,
          relations: ['pool'],
        },
        {
          name: 'pool',
          writable: true,
        },
        {
          name: 'mint',
          relations: ['pool'],
        },
        {
          name: 'vault',
          writable: true,
          relations: ['pool'],
        },
        {
          name: 'sponsorTokenAccount',
          writable: true,
        },
        {
          name: 'tokenProgram',
          address: 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb',
        },
      ],
      args: [],
    },
    {
      name: 'withdraw',
      discriminator: [183, 18, 70, 156, 148, 109, 161, 34],
      accounts: [
        {
          name: 'saver',
          signer: true,
          relations: ['position'],
        },
        {
          name: 'pool',
          writable: true,
          relations: ['position'],
        },
        {
          name: 'position',
          writable: true,
        },
        {
          name: 'mint',
          relations: ['pool'],
        },
        {
          name: 'vault',
          writable: true,
          relations: ['pool'],
        },
        {
          name: 'saverTokenAccount',
          writable: true,
        },
        {
          name: 'tokenProgram',
          address: 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb',
        },
      ],
      args: [],
    },
  ],
  accounts: [
    {
      name: 'config',
      discriminator: [155, 12, 170, 224, 30, 250, 204, 130],
    },
    {
      name: 'pool',
      discriminator: [241, 154, 109, 4, 17, 177, 109, 188],
    },
    {
      name: 'position',
      discriminator: [170, 188, 143, 228, 122, 64, 247, 208],
    },
  ],
  events: [
    {
      name: 'claimed',
      discriminator: [217, 192, 123, 72, 108, 150, 248, 33],
    },
    {
      name: 'configInitialized',
      discriminator: [181, 49, 200, 156, 19, 167, 178, 91],
    },
    {
      name: 'deposited',
      discriminator: [111, 141, 26, 45, 161, 35, 100, 57],
    },
    {
      name: 'matchFunded',
      discriminator: [1, 37, 9, 113, 47, 119, 3, 100],
    },
    {
      name: 'poolCreated',
      discriminator: [202, 44, 41, 88, 104, 220, 157, 82],
    },
    {
      name: 'positionClosed',
      discriminator: [157, 163, 227, 228, 13, 97, 138, 121],
    },
    {
      name: 'unmatchedReclaimed',
      discriminator: [28, 130, 1, 147, 9, 186, 88, 252],
    },
    {
      name: 'withdrawn',
      discriminator: [20, 89, 223, 198, 194, 124, 219, 13],
    },
  ],
  errors: [
    {
      code: 6000,
      name: 'mathOverflow',
      msg: 'Arithmetic overflow',
    },
    {
      code: 6001,
      name: 'unauthorized',
      msg: 'Only the pool sponsor can do this',
    },
    {
      code: 6002,
      name: 'wrongMint',
      msg: 'The mint does not match this pool',
    },
    {
      code: 6003,
      name: 'wrongVault',
      msg: 'The vault does not match this pool',
    },
    {
      code: 6004,
      name: 'invalidMatchBps',
      msg: 'Match ratio must be between 1 and 10000 basis points',
    },
    {
      code: 6005,
      name: 'invalidPerSaverCap',
      msg: 'Per-saver cap must be greater than zero',
    },
    {
      code: 6006,
      name: 'invalidVestingDuration',
      msg: 'Vesting period is outside the allowed range',
    },
    {
      code: 6007,
      name: 'invalidPoolWindow',
      msg: 'Deposit window must end in the future and within the allowed range',
    },
    {
      code: 6008,
      name: 'invalidMintDecimals',
      msg: 'Mint decimals are not supported',
    },
    {
      code: 6009,
      name: 'unsupportedMintExtension',
      msg: 'Mint has an extension this program does not accept',
    },
    {
      code: 6010,
      name: 'transferHookEnabled',
      msg: 'Mint has an enabled transfer hook',
    },
    {
      code: 6011,
      name: 'frozenByDefault',
      msg: 'Mint creates token accounts frozen by default',
    },
    {
      code: 6012,
      name: 'mintPaused',
      msg: 'Mint transfers are paused by the issuer',
    },
    {
      code: 6013,
      name: 'zeroAmount',
      msg: 'Amount must be greater than zero',
    },
    {
      code: 6014,
      name: 'poolEnded',
      msg: 'The deposit window has closed',
    },
    {
      code: 6015,
      name: 'poolNotEnded',
      msg: 'The pool has not ended yet',
    },
    {
      code: 6016,
      name: 'depositExceedsCap',
      msg: 'Deposit exceeds the per-saver cap',
    },
    {
      code: 6017,
      name: 'budgetExhausted',
      msg: 'The match budget is exhausted',
    },
    {
      code: 6018,
      name: 'matchBelowMinimum',
      msg: 'Match available is below the minimum requested',
    },
    {
      code: 6019,
      name: 'nothingToClaim',
      msg: 'There is no vested match to claim',
    },
    {
      code: 6020,
      name: 'alreadyWithdrawn',
      msg: 'This position has already been withdrawn',
    },
    {
      code: 6021,
      name: 'mintNotAllowed',
      msg: 'This mint is not the one this deployment allows',
    },
    {
      code: 6022,
      name: 'nothingToReclaim',
      msg: 'There is no unreserved budget to reclaim',
    },
    {
      code: 6023,
      name: 'positionStillActive',
      msg: 'The position still has a deposit or unclaimed match',
    },
  ],
  types: [
    {
      name: 'claimed',
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'pool',
            type: 'pubkey',
          },
          {
            name: 'saver',
            type: 'pubkey',
          },
          {
            name: 'amount',
            type: 'u64',
          },
          {
            name: 'totalClaimed',
            type: 'u64',
          },
        ],
      },
    },
    {
      name: 'config',
      docs: [
        "Deployment-wide settings, written once by the program's upgrade authority. There is",
        'no update instruction, so the allowed mint cannot change after `init_config`.',
      ],
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'admin',
            docs: ['The upgrade authority that initialised this deployment.'],
            type: 'pubkey',
          },
          {
            name: 'allowedMint',
            docs: [
              'The only mint a pool may hold: SPYx on mainnet, the replica on devnet.',
            ],
            type: 'pubkey',
          },
          {
            name: 'bump',
            type: 'u8',
          },
        ],
      },
    },
    {
      name: 'configInitialized',
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'admin',
            type: 'pubkey',
          },
          {
            name: 'allowedMint',
            type: 'pubkey',
          },
        ],
      },
    },
    {
      name: 'createPoolParams',
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'poolId',
            docs: ['Lets one sponsor run several pools.'],
            type: 'u64',
          },
          {
            name: 'matchBps',
            docs: ['Match per deposit in basis points; 10_000 is 1:1.'],
            type: 'u16',
          },
          {
            name: 'perSaverCap',
            docs: ['Largest deposit one saver may make, in raw units.'],
            type: 'u64',
          },
          {
            name: 'vestingSeconds',
            type: 'i64',
          },
          {
            name: 'endsAt',
            docs: ['Unix time when deposits and funding stop.'],
            type: 'i64',
          },
        ],
      },
    },
    {
      name: 'deposited',
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'pool',
            type: 'pubkey',
          },
          {
            name: 'saver',
            type: 'pubkey',
          },
          {
            name: 'amount',
            type: 'u64',
          },
          {
            name: 'matchReserved',
            type: 'u64',
          },
          {
            name: 'startedAt',
            type: 'i64',
          },
        ],
      },
    },
    {
      name: 'matchFunded',
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'pool',
            type: 'pubkey',
          },
          {
            name: 'sponsor',
            type: 'pubkey',
          },
          {
            name: 'amount',
            type: 'u64',
          },
          {
            name: 'budgetTotal',
            type: 'u64',
          },
        ],
      },
    },
    {
      name: 'pool',
      docs: [
        'One sponsor-funded match pool. All amounts are raw token units.',
        '',
        'Vault accounting, which the tests assert:',
        '`vault balance >= (budget_total - claimed) + deposits_total`.',
        'Logic never reads the vault balance, so an unsolicited transfer into the',
        'vault cannot skew it.',
      ],
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'sponsor',
            type: 'pubkey',
          },
          {
            name: 'mint',
            type: 'pubkey',
          },
          {
            name: 'vault',
            type: 'pubkey',
          },
          {
            name: 'poolId',
            type: 'u64',
          },
          {
            name: 'matchBps',
            type: 'u16',
          },
          {
            name: 'perSaverCap',
            docs: ['Largest deposit a single saver may make.'],
            type: 'u64',
          },
          {
            name: 'vestingSeconds',
            type: 'i64',
          },
          {
            name: 'createdAt',
            type: 'i64',
          },
          {
            name: 'endsAt',
            docs: [
              'Deposits and funding stop at this time; the sponsor may then reclaim unreserved budget.',
            ],
            type: 'i64',
          },
          {
            name: 'budgetTotal',
            docs: ['Match the sponsor has funded and not reclaimed.'],
            type: 'u64',
          },
          {
            name: 'reserved',
            docs: [
              'Match reserved for savers, claimed or not. Never exceeds `budget_total`.',
            ],
            type: 'u64',
          },
          {
            name: 'claimed',
            docs: ['Reserved match already paid out.'],
            type: 'u64',
          },
          {
            name: 'depositsTotal',
            docs: ['Saver principal currently held in the vault.'],
            type: 'u64',
          },
          {
            name: 'bump',
            type: 'u8',
          },
          {
            name: 'vaultBump',
            type: 'u8',
          },
        ],
      },
    },
    {
      name: 'poolCreated',
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'pool',
            type: 'pubkey',
          },
          {
            name: 'sponsor',
            type: 'pubkey',
          },
          {
            name: 'mint',
            type: 'pubkey',
          },
          {
            name: 'poolId',
            type: 'u64',
          },
          {
            name: 'matchBps',
            type: 'u16',
          },
          {
            name: 'perSaverCap',
            type: 'u64',
          },
          {
            name: 'vestingSeconds',
            type: 'i64',
          },
          {
            name: 'endsAt',
            type: 'i64',
          },
        ],
      },
    },
    {
      name: 'position',
      docs: ["One saver's stake in one pool. A saver deposits once per pool."],
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'pool',
            type: 'pubkey',
          },
          {
            name: 'saver',
            type: 'pubkey',
          },
          {
            name: 'deposited',
            docs: ['Principal still in the vault; zero once withdrawn.'],
            type: 'u64',
          },
          {
            name: 'matchReserved',
            docs: ['Match reserved for this position, after any forfeiture.'],
            type: 'u64',
          },
          {
            name: 'matchClaimed',
            type: 'u64',
          },
          {
            name: 'startedAt',
            type: 'i64',
          },
          {
            name: 'settled',
            docs: [
              'Set by `withdraw`. The unvested match is forfeited at that moment, so',
              'what remains is fully vested and vesting must not be recomputed.',
            ],
            type: 'bool',
          },
          {
            name: 'bump',
            type: 'u8',
          },
        ],
      },
    },
    {
      name: 'positionClosed',
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'pool',
            type: 'pubkey',
          },
          {
            name: 'saver',
            type: 'pubkey',
          },
        ],
      },
    },
    {
      name: 'unmatchedReclaimed',
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'pool',
            type: 'pubkey',
          },
          {
            name: 'sponsor',
            type: 'pubkey',
          },
          {
            name: 'amount',
            type: 'u64',
          },
          {
            name: 'budgetTotal',
            type: 'u64',
          },
        ],
      },
    },
    {
      name: 'withdrawn',
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'pool',
            type: 'pubkey',
          },
          {
            name: 'saver',
            type: 'pubkey',
          },
          {
            name: 'principal',
            type: 'u64',
          },
          {
            name: 'forfeited',
            type: 'u64',
          },
        ],
      },
    },
  ],
  constants: [
    {
      name: 'bpsDenominator',
      type: 'u64',
      value: '10000',
    },
    {
      name: 'configSeed',
      type: 'bytes',
      value: '[99, 111, 110, 102, 105, 103]',
    },
    {
      name: 'maxMatchBps',
      docs: ['Match ratio ceiling: 10_000 bps is a 1:1 match.'],
      type: 'u16',
      value: '10000',
    },
    {
      name: 'maxPoolWindowSeconds',
      docs: [
        'Longest deposit window a pool may declare, counted from creation.',
      ],
      type: 'i64',
      value: '157680000',
    },
    {
      name: 'maxVestingSeconds',
      type: 'i64',
      value: '157680000',
    },
    {
      name: 'mintDecimals',
      docs: [
        'Every supported mint (SPYx and the devnet replica) uses 8 decimals.',
      ],
      type: 'u8',
      value: '8',
    },
    {
      name: 'minVestingSeconds',
      docs: [
        'Floor is low on purpose so a demo pool can vest in minutes. Real pools use months.',
      ],
      type: 'i64',
      value: '30',
    },
    {
      name: 'poolSeed',
      type: 'bytes',
      value: '[112, 111, 111, 108]',
    },
    {
      name: 'positionSeed',
      type: 'bytes',
      value: '[112, 111, 115, 105, 116, 105, 111, 110]',
    },
    {
      name: 'vaultSeed',
      type: 'bytes',
      value: '[118, 97, 117, 108, 116]',
    },
  ],
};
