#!/usr/bin/env bash
# Rebuilds the program and writes its IDL into packages/types/src/program/match_pools.ts
# as a type plus a typed constant, so the dApp imports a reviewed, checked-in interface
# and never depends on programs/target.
#
# Anchor's generated type body is also a valid value literal, so the constant needs no
# cast: `export const matchPoolsIdl: MatchPools = { ... }`.
set -euo pipefail

export PATH="$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/packages/types/src/program/match_pools.ts"

cd "$ROOT/programs"
anchor build --arch v0 --ignore-keys

mkdir -p "$(dirname "$DEST")"
python3 - "$ROOT/programs/target/types/match_pools.ts" "$DEST" <<'PY'
import re, sys
source, dest = sys.argv[1], sys.argv[2]
text = open(source).read()
marker = "export type MatchPools ="
start = text.index(marker)
body = text[start + len(marker):].strip()
assert body.endswith(";"), "unexpected generated types layout"
body = body[:-1].strip()
header = (
    "// GENERATED by `pnpm program:idl` from programs/target/types/match_pools.ts.\n"
    "// Do not edit by hand. Review the diff whenever the on-chain interface changes.\n\n"
)
open(dest, "w").write(
    header
    + "export type MatchPools = " + body + ";\n\n"
    + "export const matchPoolsIdl: MatchPools = " + body + ";\n"
)
PY

cd "$ROOT"
pnpm exec prettier --write "$DEST" >/dev/null
echo "wrote $DEST"
git --no-pager diff --stat -- packages/types/src/program || true
